### ISSUE TITLE
Missing Textures

### ISSUE THREAD

**Issue by Itsyourdriver** [seagull101/Source-Hangout#1]
Missing textures in:
- Elevator shaft
- Trench area in bottom floor
- Window

**Comment by seagull101** [comment]
Yup, that should be fixed when I upload the paks.

**Comment by seagull101** [comment]
I might unpack them and upload them in a portal folder (where the assets are from)

**Comment by Itsyourdriver** [comment]
Fixed as of latest version by @seagull101 ^_^
https://driver.is-from.space/hl2_Ncjlklaxqo.jpg
https://going.to-sleep.xyz/hl2_IS9vmlT270.jpg
